---
title: "Assignment-01"
author: "mike-lid", "JebP"
date: "9/6/2021"
output: html_document
---
```{r load packages, message=FALSE}
#above line labels the code chunk as "load packages" without seeing any of the package loading messages
  library (sf)
  library(tidyverse)
  library(ggspatial)
  library(ggthemes)
  library(maptools)
```

```{r load packages, message=FALSE}
#the following data includes commercial parking locations in Cambridge, polygon data of metered parking spots, and boundaries for open space. We are curious to see the relationship between available Cambridge parking and locations of open/green space.

  commercialparking <- st_read("CommParking.geojson")
  meters <- st_read("MetParking.shp.zip")
  openspace <- st_read ("OpenSpace.shp.zip")
```

```{r}
#PLOT ONE --- UGLY MAP ----------------
parking_plot <- ggplot(commercialparking) +
  geom_sf(shape = 20, color = "#CC0066", size = 3)

parking_plot +
  geom_sf(data = meters) +
  geom_sf(data = openspace)
```

```{r}

ggplot()+
 #TITLE + AXIS LABELS
        ggtitle("CAMBRIDGE PARKING IN RELATION TO OPEN SPACE")+
        xlab("LONGITUDE")+
        ylab("LATITUDE")+

  #BASE MAP
      annotation_map_tile(
        zoomin = 0, 
        progress = "none", 
        type = "cartolight") +
  
  #DATA
      #commercial parking
        geom_sf(
        data = commercialparking, 
        aes(fill="Commercial Parking Lots"), 
        alpha = .7, 
        color = "aquamarine"
        ) +
      #metered parking
      geom_sf(
        data = meters, 
        color = "black", 
        aes(fill="Metered Parking")
        ) +
      #open space
      geom_sf(
        data = openspace, 
        aes(fill="Parks"), 
        alpha = 0.25, 
        color = "tan",
        ) +
  
  #APPEARANCE
      #themes
      scale_fill_manual(values = c("aquamarine", "black", "tan"), name = "") +
      scale_color_manual(values = c("aquamarine", "black", "tan"), name = "") +
  
      #add a scale + arrow
      annotation_scale(
        pad_x = unit(8, "cm"),
        pad_y = unit(.5, "cm"),
        plot_unit = NULL,
        bar_cols = c("black", NA),
        line_width = .125,
        height = unit(0.125, "cm"),
        text_pad = unit(0.15, "cm"),
        text_cex = 0.7,
        text_face = NULL,
        text_family = "",
        tick_height = 0.4) + 
      annotation_north_arrow(
        pad_x = unit(7, "cm"),
        pad_y = unit(.25, "cm"),
        height = unit(0.5, "cm"),
        width = unit(0.5, "cm"),
        
        #north arrow style
        style = north_arrow_orienteering(
          text_size = 1
          ))
  
  theme(panel.background = element_rect (fill = NA), 
        legend.key = element_rect(fill = NA))
```
  
```{r}
#plotting a 3in x 5in image of 300ppi
#can replace "jpeg" with "png" or "pdf"
jpeg("commercial_parking.jpg", width = 5, height = 3, units = "in", res = 300)
commercial_plot
dev.off()
```
