---
title: "Assignment-01"
author: "mike-lid", "JebP"
date: "9/6/2021"
output: html_document
---

```{r load packages, message=FALSE}
#above line labels the code chunk as "load packages" without seeing any of the package loading messages
  library (sf)
  library(tidyverse)
  library(ggspatial)
  library(ggthemes)
```

```{r load packages, message=FALSE}
#the following data includes commercial parking locations in Cambridge, polygon data of metered parking spots, and boundaries for open space. We are curious to see the relationship between available Cambridge parking and locations of open/green space. We hope that by writing "message=false", that this chunk will not appear in the knit

  commercialparking <- st_read("CommParking.geojson")
  meters <- st_read("MetParking.shp.zip")
  openspace <- st_read ("OpenSpace.shp.zip")
```

```{r}
parking_plot <- ggplot(commercialparking) +
  geom_sf(shape = 20, color = "#CC0066", size = 3)
parking_plot +
  geom_sf(data = meters) +
  geom_sf(data = openspace)
  
```


```{r}
#CHANGE COLORS
parking_plot <- ggplot(commercialparking) +
  geom_sf(shape = 20, color = "blue", size = 4)
parking_plot +
  geom_sf(data = meters, color = "darkorange") +
  geom_sf(data = openspace, fill = "forestgreen", color = NA)
```

#changing symbology again
```{r}

#finding centroids of metered parking polygons
ggplot(st_centroid(meters)) +
  geom_sf(
    size = 0.5,
    shape = 20,
    color = "brown1",
    alpha = 0.2    
    ) +
  
#TITLE
  ggtitle("Cambridge Park(ing)") +
  
#BASE MAP
  
#DATA 
   geom_sf(
    data = openspace, 
    color = NA, 
    fill = "forestgreen"
    ) +
  geom_sf(
    data = commercialparking, 
    shape = 20, 
    size = 3, 
    color = "brown1"
    ) +
  
  
  theme_void()

  
```
#changing symbology again
```{r}
ggplot() +
  
ggtitle("Cambridge Park(ing)") +
  
#BASE MAP
    annotation_map_tile(
    zoomin = 0, 
    progress = "none", 
    type = "cartodark") +
    geom_sf() +
    labs(caption = "Map tiles and data by OpenStreetMap") +
  
#DATA 
   geom_sf(
    data = openspace, 
    color = NA, 
    alpha = 0.6,
    aes(fill = "Open Space")
    ) +
  geom_sf(
    data = meters, 
    fill = "white",
    aes(color = "Parking Meters")
    ) +
  geom_sf(
    data = commercialparking, 
    shape = 20, 
    size = 3, 
    aes(color = "Commercial Parking")
    ) +
  scale_color_manual(values = c("deeppink", "darkviolet"), name = "") +
  scale_fill_manual(values = "chartreuse", name = "") +
  
  theme_void()

  
```

#changing symbology again
```{r}
ggplot() +
  
ggtitle("Cambridge Park(ing)") +
  
#BASE MAP
    annotation_map_tile(
    zoomin = 0, 
    progress = "none", 
    type = "cartolight") +
    geom_sf() +
    labs(caption = "Map tiles by OpenStreetMap; data from City of Cambridge") +
  
#DATA 
   geom_sf(
    data = openspace, 
    color = NA, 
    alpha = 0.5,
    aes(fill = "Open Space")
    ) +
  geom_sf(
    data = meters, 
    color = NA,
    shape = NA,
    aes(fill = "Metered Parking")
    ) +
  geom_sf(
    data = commercialparking, 
    shape = 3, 
    size = 2, 
    fill = NA,
    aes(color = "Commercial Parking")
    ) +
  
  scale_fill_manual(values = c("brown3", "forestgreen"), name = "") +
  scale_color_manual(values = "brown1", name = "") +
  
  theme_void()
```

#changing symbology again - very ugly version
```{r}
ggplot() +
  
ggtitle("Cambridge Park(ing)") +
  
#BASE MAP
  
    annotation_map_tile(
    zoomin = 0, 
    progress = "none", 
    type = "stamenwatercolor") +
    geom_sf() +
    labs(caption = "Map tiles by Stamen Design. Data by OpenStreetMap") +

 
#DATA 
   geom_sf(
    data = openspace, 
    color = NA, 
    alpha = 0.5,
    aes(fill = "Open Space")
    ) +
  geom_sf(
    data = meters, 
    color = NA,
    shape = NA,
    aes(fill = "Metered Parking")
    ) +
  geom_sf(
    data = commercialparking, 
    shape = 11, 
    size = 5, 
    fill = NA,
    aes(color = "Commercial Parking")
    ) +
  
  scale_fill_manual(values = c("brown1", "blue"), name = "") +
  scale_color_manual(values = "brown1", name = "") +
  
  theme_void()
```






```{r}
#plotting a 3in x 5in image of 300ppi
#can replace "jpeg" with "png" or "pdf"
jpeg("commercial_parking.jpg", width = 5, height = 3, units = "in", res = 300)

dev.off()
commercial_plot
```


